# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\coding\CPP\OPENGL\JBEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\coding\CPP\OPENGL\JBEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\coding\CPP\OPENGL\JBEngine\CMakeFiles C:\coding\CPP\OPENGL\JBEngine\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\coding\CPP\OPENGL\JBEngine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P C:\coding\CPP\OPENGL\JBEngine\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_opengl_app

# Build rule for target.
my_opengl_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 my_opengl_app
.PHONY : my_opengl_app

# fast build rule for target.
my_opengl_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/build
.PHONY : my_opengl_app/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty\glfw-3.4\src\CMakeFiles\glfw.dir\build.make thirdparty/glfw-3.4/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty\glfw-3.4\src\CMakeFiles\update_mappings.dir\build.make thirdparty/glfw-3.4/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty\glad\CMakeFiles\glad.dir\build.make thirdparty/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty\imgui\CMakeFiles\imgui.dir\build.make thirdparty/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

src/Camera.obj: src/Camera.cpp.obj
.PHONY : src/Camera.obj

# target to build an object file
src/Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Camera.cpp.obj
.PHONY : src/Camera.cpp.obj

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/DebugLight.obj: src/DebugLight.cpp.obj
.PHONY : src/DebugLight.obj

# target to build an object file
src/DebugLight.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/DebugLight.cpp.obj
.PHONY : src/DebugLight.cpp.obj

src/DebugLight.i: src/DebugLight.cpp.i
.PHONY : src/DebugLight.i

# target to preprocess a source file
src/DebugLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/DebugLight.cpp.i
.PHONY : src/DebugLight.cpp.i

src/DebugLight.s: src/DebugLight.cpp.s
.PHONY : src/DebugLight.s

# target to generate assembly for a file
src/DebugLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/DebugLight.cpp.s
.PHONY : src/DebugLight.cpp.s

src/Framebuffer.obj: src/Framebuffer.cpp.obj
.PHONY : src/Framebuffer.obj

# target to build an object file
src/Framebuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Framebuffer.cpp.obj
.PHONY : src/Framebuffer.cpp.obj

src/Framebuffer.i: src/Framebuffer.cpp.i
.PHONY : src/Framebuffer.i

# target to preprocess a source file
src/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Framebuffer.cpp.i
.PHONY : src/Framebuffer.cpp.i

src/Framebuffer.s: src/Framebuffer.cpp.s
.PHONY : src/Framebuffer.s

# target to generate assembly for a file
src/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Framebuffer.cpp.s
.PHONY : src/Framebuffer.cpp.s

src/Mesh.obj: src/Mesh.cpp.obj
.PHONY : src/Mesh.obj

# target to build an object file
src/Mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Mesh.cpp.obj
.PHONY : src/Mesh.cpp.obj

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/PbrBall.obj: src/PbrBall.cpp.obj
.PHONY : src/PbrBall.obj

# target to build an object file
src/PbrBall.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/PbrBall.cpp.obj
.PHONY : src/PbrBall.cpp.obj

src/PbrBall.i: src/PbrBall.cpp.i
.PHONY : src/PbrBall.i

# target to preprocess a source file
src/PbrBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/PbrBall.cpp.i
.PHONY : src/PbrBall.cpp.i

src/PbrBall.s: src/PbrBall.cpp.s
.PHONY : src/PbrBall.s

# target to generate assembly for a file
src/PbrBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/PbrBall.cpp.s
.PHONY : src/PbrBall.cpp.s

src/Renderer.obj: src/Renderer.cpp.obj
.PHONY : src/Renderer.obj

# target to build an object file
src/Renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Renderer.cpp.obj
.PHONY : src/Renderer.cpp.obj

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/ResourceManager.obj: src/ResourceManager.cpp.obj
.PHONY : src/ResourceManager.obj

# target to build an object file
src/ResourceManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/ResourceManager.cpp.obj
.PHONY : src/ResourceManager.cpp.obj

src/ResourceManager.i: src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/Scene.obj: src/Scene.cpp.obj
.PHONY : src/Scene.obj

# target to build an object file
src/Scene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Scene.cpp.obj
.PHONY : src/Scene.cpp.obj

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shader.obj: src/Shader.cpp.obj
.PHONY : src/Shader.obj

# target to build an object file
src/Shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Shader.cpp.obj
.PHONY : src/Shader.cpp.obj

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Skybox.obj: src/Skybox.cpp.obj
.PHONY : src/Skybox.obj

# target to build an object file
src/Skybox.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Skybox.cpp.obj
.PHONY : src/Skybox.cpp.obj

src/Skybox.i: src/Skybox.cpp.i
.PHONY : src/Skybox.i

# target to preprocess a source file
src/Skybox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Skybox.cpp.i
.PHONY : src/Skybox.cpp.i

src/Skybox.s: src/Skybox.cpp.s
.PHONY : src/Skybox.s

# target to generate assembly for a file
src/Skybox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Skybox.cpp.s
.PHONY : src/Skybox.cpp.s

src/Texture.obj: src/Texture.cpp.obj
.PHONY : src/Texture.obj

# target to build an object file
src/Texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Texture.cpp.obj
.PHONY : src/Texture.cpp.obj

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/Water.obj: src/Water.cpp.obj
.PHONY : src/Water.obj

# target to build an object file
src/Water.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Water.cpp.obj
.PHONY : src/Water.cpp.obj

src/Water.i: src/Water.cpp.i
.PHONY : src/Water.i

# target to preprocess a source file
src/Water.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Water.cpp.i
.PHONY : src/Water.cpp.i

src/Water.s: src/Water.cpp.s
.PHONY : src/Water.s

# target to generate assembly for a file
src/Water.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/Water.cpp.s
.PHONY : src/Water.cpp.s

src/imgui/imgui.obj: src/imgui/imgui.cpp.obj
.PHONY : src/imgui/imgui.obj

# target to build an object file
src/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui.cpp.obj
.PHONY : src/imgui/imgui.cpp.obj

src/imgui/imgui.i: src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.i

# target to preprocess a source file
src/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.cpp.i

src/imgui/imgui.s: src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.s

# target to generate assembly for a file
src/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.cpp.s

src/imgui/imgui_demo.obj: src/imgui/imgui_demo.cpp.obj
.PHONY : src/imgui/imgui_demo.obj

# target to build an object file
src/imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_demo.cpp.obj
.PHONY : src/imgui/imgui_demo.cpp.obj

src/imgui/imgui_demo.i: src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.i

# target to preprocess a source file
src/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.cpp.i

src/imgui/imgui_demo.s: src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.s

# target to generate assembly for a file
src/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.cpp.s

src/imgui/imgui_draw.obj: src/imgui/imgui_draw.cpp.obj
.PHONY : src/imgui/imgui_draw.obj

# target to build an object file
src/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_draw.cpp.obj
.PHONY : src/imgui/imgui_draw.cpp.obj

src/imgui/imgui_draw.i: src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.i

# target to preprocess a source file
src/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.cpp.i

src/imgui/imgui_draw.s: src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.s

# target to generate assembly for a file
src/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.cpp.s

src/imgui/imgui_impl_glfw.obj: src/imgui/imgui_impl_glfw.cpp.obj
.PHONY : src/imgui/imgui_impl_glfw.obj

# target to build an object file
src/imgui/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_impl_glfw.cpp.obj
.PHONY : src/imgui/imgui_impl_glfw.cpp.obj

src/imgui/imgui_impl_glfw.i: src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.cpp.i

src/imgui/imgui_impl_glfw.s: src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.cpp.s

src/imgui/imgui_impl_opengl3.obj: src/imgui/imgui_impl_opengl3.cpp.obj
.PHONY : src/imgui/imgui_impl_opengl3.obj

# target to build an object file
src/imgui/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_impl_opengl3.cpp.obj
.PHONY : src/imgui/imgui_impl_opengl3.cpp.obj

src/imgui/imgui_impl_opengl3.i: src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.cpp.i

src/imgui/imgui_impl_opengl3.s: src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.cpp.s

src/imgui/imgui_tables.obj: src/imgui/imgui_tables.cpp.obj
.PHONY : src/imgui/imgui_tables.obj

# target to build an object file
src/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_tables.cpp.obj
.PHONY : src/imgui/imgui_tables.cpp.obj

src/imgui/imgui_tables.i: src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.i

# target to preprocess a source file
src/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.cpp.i

src/imgui/imgui_tables.s: src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.s

# target to generate assembly for a file
src/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.cpp.s

src/imgui/imgui_widgets.obj: src/imgui/imgui_widgets.cpp.obj
.PHONY : src/imgui/imgui_widgets.obj

# target to build an object file
src/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_widgets.cpp.obj
.PHONY : src/imgui/imgui_widgets.cpp.obj

src/imgui/imgui_widgets.i: src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.i

# target to preprocess a source file
src/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.cpp.i

src/imgui/imgui_widgets.s: src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.s

# target to generate assembly for a file
src/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\my_opengl_app.dir\build.make CMakeFiles/my_opengl_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... update_mappings
	@echo ... glad
	@echo ... glfw
	@echo ... imgui
	@echo ... my_opengl_app
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/DebugLight.obj
	@echo ... src/DebugLight.i
	@echo ... src/DebugLight.s
	@echo ... src/Framebuffer.obj
	@echo ... src/Framebuffer.i
	@echo ... src/Framebuffer.s
	@echo ... src/Mesh.obj
	@echo ... src/Mesh.i
	@echo ... src/Mesh.s
	@echo ... src/PbrBall.obj
	@echo ... src/PbrBall.i
	@echo ... src/PbrBall.s
	@echo ... src/Renderer.obj
	@echo ... src/Renderer.i
	@echo ... src/Renderer.s
	@echo ... src/ResourceManager.obj
	@echo ... src/ResourceManager.i
	@echo ... src/ResourceManager.s
	@echo ... src/Scene.obj
	@echo ... src/Scene.i
	@echo ... src/Scene.s
	@echo ... src/Shader.obj
	@echo ... src/Shader.i
	@echo ... src/Shader.s
	@echo ... src/Skybox.obj
	@echo ... src/Skybox.i
	@echo ... src/Skybox.s
	@echo ... src/Texture.obj
	@echo ... src/Texture.i
	@echo ... src/Texture.s
	@echo ... src/Water.obj
	@echo ... src/Water.i
	@echo ... src/Water.s
	@echo ... src/imgui/imgui.obj
	@echo ... src/imgui/imgui.i
	@echo ... src/imgui/imgui.s
	@echo ... src/imgui/imgui_demo.obj
	@echo ... src/imgui/imgui_demo.i
	@echo ... src/imgui/imgui_demo.s
	@echo ... src/imgui/imgui_draw.obj
	@echo ... src/imgui/imgui_draw.i
	@echo ... src/imgui/imgui_draw.s
	@echo ... src/imgui/imgui_impl_glfw.obj
	@echo ... src/imgui/imgui_impl_glfw.i
	@echo ... src/imgui/imgui_impl_glfw.s
	@echo ... src/imgui/imgui_impl_opengl3.obj
	@echo ... src/imgui/imgui_impl_opengl3.i
	@echo ... src/imgui/imgui_impl_opengl3.s
	@echo ... src/imgui/imgui_tables.obj
	@echo ... src/imgui/imgui_tables.i
	@echo ... src/imgui/imgui_tables.s
	@echo ... src/imgui/imgui_widgets.obj
	@echo ... src/imgui/imgui_widgets.i
	@echo ... src/imgui/imgui_widgets.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P C:\coding\CPP\OPENGL\JBEngine\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

